### ISSUE TITLE
Adds first pass example using movie example from metaflow

### ISSUE THREAD

**Issue by HamiltonRepoMigrationBot** [DAGWorks-Inc/hamilton#13]
<a href="https://github.com/skrawcz"><img src="https://avatars.githubusercontent.com/u/2328071?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [skrawcz](https://github.com/skrawcz)**
_Thursday Dec 23, 2021 at 02:10 GMT_
_Originally opened as https://github.com/stitchfix/hamilton/pull/32_

----

Goal of this PR is to provide more extensive examples.

Inspiration is from:
https://github.com/Netflix/metaflow/blob/master/metaflow/tutorials/01-playlist/playlist.py

Two interesting things to note here:

1. We could have the driver do the loading of the CSV, or we could have a function to do it.
2. Filter operations are easiest to happen in the driver I think. Not to say you can't do it,
we'd just need better logic around creating the dataframe, and not trying to combine series
with various index lengths. Hmm.

## Additions

- Examples

## Removals

- N/A

## Changes

- N/A

## Testing

1. The example works. Tested locally.

## Todos

- [] add more examples and see if this makes sense.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the dev standards.
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Python

- [x] python 3.6
- [x] python 3.7

----

_**[skrawcz](https://github.com/skrawcz)** included the following code: https://github.com/stitchfix/hamilton/pull/32/commits_

**Comment by elijahbenizzy** [comment]
@skrawcz this was an old PR. Still relevant?

**Comment by elijahbenizzy** [comment]
This is a PR from the old repository
