### ISSUE TITLE
Lazy config evaluation

### ISSUE THREAD

**Issue by HamiltonRepoMigrationBot** [DAGWorks-Inc/hamilton#18]
<a href="https://github.com/elijahbenizzy"><img src="https://avatars.githubusercontent.com/u/3886307?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [elijahbenizzy](https://github.com/elijahbenizzy)**
_Monday Feb 07, 2022 at 03:51 GMT_
_Originally opened as https://github.com/stitchfix/hamilton/pull/64_

----

[Short description explaining the high-level reason for the pull request]

## Additions

-

## Removals

-

## Changes

-

## Testing

1.

## Screenshots
If applicable

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [TODO link to standards]()
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Python

- [ ] python 3.6
- [ ] python 3.7

----

_**[elijahbenizzy](https://github.com/elijahbenizzy)** included the following code: https://github.com/stitchfix/hamilton/pull/64/commits_

**Comment by HamiltonRepoMigrationBot** [comment]
<a href="https://github.com/elijahbenizzy"><img src="https://avatars.githubusercontent.com/u/3886307?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elijahbenizzy](https://github.com/elijahbenizzy)**
_Monday Feb 07, 2022 at 03:55 GMT_

----

Need to add tests/figure out what to test. Hopefully this demonstrates the issue. IMO chainmap is actually better here -- supporting a lazyconfig is reasonable. That said, I'd prefer the simplicity with a dictionary.

**Comment by HamiltonRepoMigrationBot** [comment]
<a href="https://github.com/elijahbenizzy"><img src="https://avatars.githubusercontent.com/u/3886307?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elijahbenizzy](https://github.com/elijahbenizzy)**
_Monday Feb 07, 2022 at 03:58 GMT_

----

Pros of this:
1. It allows lazily evaluated configs
2. Its idiomatic -- types are only as constricted as they need to be (E.G. why does config have to be a dict?)
3. It solves the problem a customer has

Cons of this:
1. We can do less with the config/inputs - E.G. if we want to store them somewhere or print them out we'll be running up against the same problem.
2. Added complexity for a specific use-case

**Comment by elijahbenizzy** [comment]
I don't think this is something we particularly want to handle now... Configs shouldn't be particularly complicated -- anything too complex should fit in the DAG itself. 

If there's a complex process that determines *how* to shape it, we can figure that out. In the case o f the original motivation for this problem, we ended up just loading everything in parallel upfront.
