### ISSUE TITLE
[good first issue - beginner] Pandas Readers & Writers

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#284]
**Is your feature request related to a problem? Please describe.**
We need to add more Pandas Readers & Writers (Savers & Loaders in our internal parlance).

**Describe the solution you'd like**
We need to have readers & if appropriate, writers, covering:

- [x] #409
- [x] #292 (assigned to @benhhack)
- [x] #407 (assigned to @bengineerdavis)
- [ ] pandas fwf
- [x] #342 ()
- [x] #341 (assigned to @bryangalindo)
- [x] #369 (assigned to @JoJo10Smith)
- [x] #352 (assigned to @JoJo10Smith )
- [ ] pandas hdf
- [x] #384 (assigned to @JoJo10Smith )
- [x] #406
- [x] pandas orc (assigned to @JoJo10Smith )
- [ ] pandas sas
- [x] pandas spss
- [x] #355 (assigned to @bryangalindo )
- [x] #375 
- [x] #377 (assigned to @JoJo10Smith )
- [ ] [Latex writer](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html)

We should cover I/O as listed [here](https://pandas.pydata.org/docs/reference/io.html).

**Additional context**
We need to start building wrappers around the common ways people will want to save/load data. That way they'll have off the shelf ways to get onto Hamilton easily.

# If you're interested in contributing

If you are interested in contributing, picking up one of the above should be straightforward.

1. Ask for one, and we'll assign it.
2. We'll create an issue for you.
3. We'll then work with you on that issue.

In terms of effort, for an example of a desired class, see [this code](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L43-L147). It basically involves:

1. Reading the subsequent documentation.
2. Creating the right class.
3. Creating some tests for it.
4. Creating an example to put into our examples repository.

**Comment by benhhack** [comment]
Hey there, I would love to give this a go with one of the pandas i/o methods. I'm new to contributing on GitHub so I appreciate the cooperative work.

**Comment by elijahbenizzy** [comment]
> Hey there, I would love to give this a go with one of the pandas i/o methods. I'm new to contributing on GitHub so I appreciate the cooperative work.

@benhhack 

That would be great! Hopefully there are enough examples to get you started -- let us know what you need above that. No judgement if you use gpt-* to help you out as well -- I've found its helpful for translation/repetetive tasks like this.

**Comment by skrawcz** [comment]
> Hey there, I would love to give this a go with one of the pandas i/o methods. I'm new to contributing on GitHub so I appreciate the cooperative work.

@benhhack yeah thanks for offering to help! Just to make sure this indeed is the right issue to get started with, what's your comfort level with python & pandas?

**Comment by benhhack** [comment]
> 

Quite familiar with using both, you can check out my repos to see my level. Never really done anything like this before though, so I'm quite interested to see how it goes.

**Comment by skrawcz** [comment]
> > 
> 
> Quite familiar with using both, you can check out my repos to see my level. Never really done anything like this before though, so I'm quite interested to see how it goes.

Cool. I would take a look at https://pandas.pydata.org/docs/reference/io.html, pick one, and then we can claim that here and create an issue to move discussion to. Which one would you like?

**Comment by benhhack** [comment]
> > > 
> > 
> > 
> > Quite familiar with using both, you can check out my repos to see my level. Never really done anything like this before though, so I'm quite interested to see how it goes.
> 
> Cool. I would take a look at https://pandas.pydata.org/docs/reference/io.html, pick one, and then we can claim that here and create an issue to move discussion to. Which one would you like?

Looking at that they all seem equally vague, haha. You can assign me to whichever you'd feel is most appropriate/best to start on.

**Comment by skrawcz** [comment]
> Looking at that they all seem equally vague, haha. You can assign me to whichever you'd feel is most appropriate/best to start on.

Sure. @benhhack mind commenting on #292 so I can assign it to you?

**Comment by benhhack** [comment]
> > Looking at that they all seem equally vague, haha. You can assign me to whichever you'd feel is most appropriate/best to start on.
> 
> Sure. @benhhack mind commenting on #292 so I can assign it to you?

Have commented :))

**Comment by skrawcz** [comment]
@benhhack https://github.com/DAGWorks-Inc/hamilton/issues/292 is open for you, if you wanted to comment on it.

**Comment by JoJo10Smith** [comment]
@skrawcz I've taken a look at the other tickets and I could try the XML read and write class. The classes shouldn't be too difficult but I will reach out if I need help with the testing. 

Thanks
Jordan

**Comment by skrawcz** [comment]
> @skrawcz I've taken a look at the other tickets and I could try the XML read and write class. The classes shouldn't be too difficult but I will reach out if I need help with the testing.
> 
> Thanks Jordan

@JoJo10Smith if you wanted to comment on https://github.com/DAGWorks-Inc/hamilton/issues/352 I can assign it to you. Thanks!

**Comment by skrawcz** [comment]
@bryangalindo mind commenting on https://github.com/DAGWorks-Inc/hamilton/issues/355 so I can assign it to you. I missed doing that earlier, sorry about that.

**Comment by JoJo10Smith** [comment]
@skrawcz I could take the HTML read and write class next.

Thanks
Jordan

**Comment by skrawcz** [comment]
> @skrawcz I could take the HTML read and write class next.
> 
> Thanks Jordan

@JoJo10Smith please comment on #369  :)

**Comment by bryangalindo** [comment]
@skrawcz i can start working on pandas gbq!

**Comment by skrawcz** [comment]
> @skrawcz i can start working on pandas gbq!

Please comment on https://github.com/DAGWorks-Inc/hamilton/issues/375 -- note this one will require a GCP account I think.

**Comment by JoJo10Smith** [comment]
@skrawcz I can take on Stata next.

**Comment by skrawcz** [comment]
> @skrawcz I can take on pandas Stata next.

@JoJo10Smith please comment on #377

**Comment by JoJo10Smith** [comment]
@skrawcz I'll take Feather next.

Thanks 
Jordan

**Comment by skrawcz** [comment]
> @skrawcz I'll take Feather next.
> 
> Thanks Jordan

https://github.com/DAGWorks-Inc/hamilton/issues/384 🙇 .

**Comment by 149189** [comment]
Hey skrawcz! I would like to work on the Panda Table I have already made many pandas dataframes and would like to work on this project.

**Comment by flaviassantos** [comment]
@skrawcz can I take 'pandas parquet'?

**Comment by skrawcz** [comment]
thanks @flaviassantos you should be all set. If you have questions put them in issue https://github.com/DAGWorks-Inc/hamilton/issues/406.

@149189 please comment on https://github.com/DAGWorks-Inc/hamilton/issues/407 to have me assign that to you. If have questions we can have the conversation there.

**Comment by JoJo10Smith** [comment]
@skrawcz I'll take csv next

Thanks 
Jordan

**Comment by skrawcz** [comment]
@JoJo10Smith https://github.com/DAGWorks-Inc/hamilton/issues/409 is up. thanks!

**Comment by swapdewalkar** [comment]
Created Spss for https://github.com/DAGWorks-Inc/hamilton/issues/813
