### ISSUE TITLE
Umbrella Issue: Lifecycle Adapter Ideas

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#786]
**Is your feature request related to a problem? Please describe.**
We have the lifecycle API. We can include more adapters, more easily now!

Here's a list of ideas:

- [ ] Profiler. One that does things similar to what's listed in #27 .
- [ ] Slack notifier. Have one that can notify a slack channel on error.
- [ ] Provide an alternate Pandera implementation using an adapter & tags.
- [ ] Provide a pydantic validator if functions are annotated with pydantic objects

**Additional context**
Please mention which idea you're interested in so that we can then flesh out an issue.

**Comment by swapdewalkar** [comment]
@skrawcz  I have started on slack notifier, can you create a ticket for the same

**Comment by skrawcz** [comment]
> @skrawcz I have started on slack notifier, can you create a ticket for the same

👍 Comment on #794 and I can assign it.
